name: pap
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.1
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.2
  firebase_database: ^9.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/ipeLogo.png
    - assets/images/rfidScanner.png
    - assets/images/logout.png
    - assets/images/militar.png
    - assets/images/professor.png
    - assets/images/funcionario.png
    - assets/images/aluno.png
    

